apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-smb-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  resources:
    requests:
      storage: 1Gi
