all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            k3s-master:
              ansible_host: 192.168.100.10
        workers:
          hosts:
            k3s-gpu-worker:
              ansible_host: 192.168.100.11
            k3s-worker:
              ansible_host: 192.168.100.12
      vars:
        ansible_user: ubuntu
        ansible_python_interpreter: /usr/bin/python3
